(lang dune 3.16)

(name craigar)

(generate_opam_files true)

(source
 (github benmandrew/craigar))

(authors "Ben Andrew")

(maintainers "Ben Andrew")

(license MIT)

(documentation https://url/to/documentation)

(package
 (name craigar)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml dune)
 (tags
  (topics "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
